---
title: "README"
output: pdf_document
---

## Getting and Cleaning Data Course Project
This repository contains files for the peer-graded assignment: Getting and Cleaning Data Course Project.

## File description
1) "script.R": The script file contains all the R codes that transform the raw data into 2 tidy data frame files (i.e. "tidyTable.csv" and "tidyTable2.csv").

2) "CodeBook.Rmd": The code book that describes the raw data files, the variables that were assigned in the "script.R", the path of merging all the data files into a single data frame, the approach that changes the column names to be more informative, and the method to summarize column mean grouped by "object" and "activity".

3) "tidyTable.csv": The tidy table generated by merging all the raw data, selecting columns with "mean" and "std", and changing the column names to be more informative.

4) "tidyTable2.csv": Using the "tidyTable.csv", the "tidyTable2.csv" summarizes column mean grouped by "object" and "activity".
